stages:
    - setup
    - seed

image: docker:latest

services:
    - docker:dind

# Can use UI to hide passwords
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_USER: willwangkelda
    KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
    HELM_URL: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    KUBE_NAMESPACE: hotrod
    REDIS_PASS: keldakelda
    POSTGRES_USER: hotrod
    POSTGRES_PASS: keldakelda

before_script:
    - apk update && apk add curl bash openssl
    - curl -LO $KUBECTL_URL
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - cat $KUBECONFIG > $HOME/.kube/config
    - curl $HELM_URL | bash
    - helm init --client-only

redis:
    stage: setup
    environment:
        name: StageEnv
    script:
    - helm upgrade --install
      --name hotrod
      --set cluster.slaveCount=2
      --set password=$REDIS_PASS
      --namespace $KUBE_NAMESPACE
      --wait
      --recreate-pods
      stable/redis

postgres:
    stage: setup
    environment:
        name: StageEnv
    script:
    - helm upgrade --install
      --name hotrod
      --set postgresUser=$POSTGRES_USER
      --set password=$POSTGRES_PASS
      --namespace $KUBE_NAMESPACE
      --wait
      --recreate-pods
      stable/postgresql

build:
    stage: setup
    before_script:
    - echo "skip install kubectl and helm"
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull $DOCKER_USER/hotrod-seed
    - docker build -t $DOCKER_USER/hotrod-seed --cache-from $DOCKER_USER/hotrod-seed scripts/
    - docker push $DOCKER_USER/hotrod-seed

seed:
    stage: seed
    script:
    - kubectl apply -f deploy/seed.yaml --namespace $KUBE_NAMESPACE
    - kubectl set env job/seed
      POSTGRES_USER=$POSTGRES_USER
      POSTGRES_PASS=$POSTGRES_PASS
      REDIS_MASTER_PASSWORD=$REDIS_PASS