stages:
    - setup

image: docker:latest

# Can use UI to hide passwords
variables:
    DOCKER_DRIVER: overlay2
    KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
    HELM_URL: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    REDIS_PASS: keldakelda
    POSTGRES_USER: hotrod
    POSTGRES_PASS: keldakelda

before_script:
    - apk update && apk add curl bash openssl
    - curl -LO $KUBECTL_URL
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - cat $KUBECONFIG > $HOME/.kube/config
    - curl $HELM_URL | bash
    - helm init --client-only

redis:
    stage: setup
    environment:
        name: StageEnv
    script:
    - helm install
      --set cluster.slaveCount=2
      --set password=$REDIS_PASS
      --namespace $KUBE_NAMESPACE
      stable/redis

postgres:
    stage: setup
    environment:
        name: StageEnv
    script:
    - helm install
      --set postgresUser=$POSTGRES_USER
      --set password=$POSTGRES_PASS
      --namespace $KUBE_NAMESPACE
      stable/postgresql