apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    spec:
      containers:
      - name: seed
        image: registry.hub.docker.com/willwangkelda/hotrod-seed
        command: ["make",  "seed"]
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_USER
          value: POSTGRES_USER_VALUE
        - name: POSTGRES_PASS
          value: POSTGRES_PASS_VALUE
        - name: REDIS_PASS
          value: REDIS_PASS_VALUE
      restartPolicy: Never
  backoffLimit: 4